name: Deploy to VPS

on:
  push:
    branches:
      - main  # Скрипт сработает только при пуше в основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/your/app  # Путь к приложению на сервере
            git pull origin main
            docker compose up -d --build  # Пересобирает и запускает контейнеры