name: Deploy to VPS

on:
  push:
    branches:
      - main  # Скрипт сработает только при пуше в основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Переходим в папку с проектом
            cd app  # Путь к приложению на сервере
            
            # Получаем последние изменения из репозитория и обновляем код
            git pull origin main
            
            # Перезапускаем Docker-сервисы
            docker compose down
            docker compose up -d --build